#!/bin/bash

WALLPAPER=$(cat ~/dotfiles/eww/scripts/.wallpaper-actual 2>/dev/null || echo "/home/alonso/Descargas/mi_fondo.png")

case "$1" in
    light)
        matugen image "$WALLPAPER" -m light --source-color-index 0
        ;;
    dark)
        matugen image "$WALLPAPER" -m dark --source-color-index 0
        ;;
    type)
        case "$2" in
            vibrant)
                matugen image "$WALLPAPER" -t scheme-vibrant --source-color-index 0
                ;;
            expressive)
                matugen image "$WALLPAPER" -t scheme-fruit-salad --source-color-index 0
                ;;
            monochrome)
                matugen image "$WALLPAPER" -t scheme-monochrome --source-color-index 0
                ;;
        esac
        ;;
esac

hyprctl reload

sleep 0.5 && eww kill && eww open bar &
