windowrule {
    name = sidebar_setup
    match:class = eww-sidebar
    float = on
    no_focus = true
    pin = on
}

windowrule {
    name = sidebar_position
    match:class = eww-sidebar
    move = 100% 0
}
