$primary = 0xff{{colors.primary.default.hex_stripped}}
$background = 0xff{{colors.surface.default.hex_stripped}}
$border_glow = 0xff{{colors.primary.default.hex_stripped}}
$border_shine = 0xff{{colors.on_primary.default.hex_stripped}}
